language: node_js
node_js: "stable"

dist: bionic

before_install:
  - stty cols 80

addons:
  firefox: latest
  chrome: stable
  
notifications:
  email:
    recipients:
      - schowdhury610@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
